export const strings = {
  calmotive: 'کالموتیو',
  welcomeToCalmotive: 'به کالموتیو خوش آمدید.',
  lets_start: 'شروع کنیم 🏁',
  u_got_account: 'از قبل حساب داری؟',
  login: 'وارد شو',
  phoneNumber: 'تلفن همراه:',
  enterCode: 'کد پیامکی را وارد کنید:',
  homepage: {
    new_items: 'تازه ها',
    sleep: 'خواب',
    breath: 'تنفس',
    course: 'دوره',
    podcasts: 'پادکست',
  },
  musics: {
    wind: 'باد',
    fire: 'آتش',
    rain: 'باران',
    cows: 'گاو',
    bell: 'زنگوله',
    birds: 'پرندگان',
    car: 'ماشین',
    water_walk: 'قدم در آب',
    jungle: 'جنگل',
    ocean: 'اقیانوس',
    river: 'رودخانه',
    thunder: 'رعد و برق',
  },
};
